name: "generate-tag"
description: |
  description: "Generate unique tags for artifacts"
  local: true
inputs:
  tag-type:
    required: true
    default: "hyphenated-alphanumeric-tag"
    description: |
      The type of tag to generate.

      Tag types supported:
        - 'punctuated-timestamp-tag' (e.g., '20231130.145802')
        - 'hyphenated-alphanumeric-tag' (e.g., '20231130-145834z-1658821493-abcd1234-main')
  tag-prefix:
    description: "An optional prefix to add to the generated tag."
  max-length:
    default: "256"
    description: "The max length of the generated tag"
  add-automatic-prefix:
    default: ${{ github.ref != format('refs/heads/{0}', github.event.repository.default_branch) }}
    description: |
      A boolean that describes whether to add an additional prefix to a tag or not.

      This allows you to more easily create cleanup policies (e.g., ECR Lifecycle Policies)
      that target artifacts that originate from non-default branches.

      NOTE: This only affects a tag of type 'hyphenated-alphanumeric-tag'.

      Default: An additional prefix is added to a tag generated from non-default branches.
outputs:
  tag:
    description: "The generated tag"
runs:
  using: "node24"
  main: "dist/index.mjs"
