name: "parse-config"
description: |
  description: "Parse and validate a JSON configuration and expose the configuration as separate outputs"
  local: true
inputs:
  config-file:
    description: |
      The path to a JSON configuration file.

      NOTE: Mutually exclusive with parameter 'config'.
    default: ".cicd.json"
  config:
    description: |
      Configuration passed in as a serialized JSON object.

      NOTE: Mutually exclusive with parameter 'config-file'.

      Example:
        config: |
          {
            "foo": "bar",
            "bar": "baz"
          }
outputs:
  version:
    description: "The version of the configuration schema, parsed from the configuration"
  accountId:
    description: "The AWS account ID, parsed from the configuration"
  roleName:
    description: "The name of the AWS IAM Role to be used by GHA for trunk branch, parsed from the configuration"
  limitedRoleName:
    description: "The name of the AWS IAM Role to be used by GHA for non-trunk branches, parsed from the configuration"
  artifactBucket:
    description: "The name of the bucket where build artifacts are stored, parsed from the configuration"
  ecrRepository:
    description: "The name of the ECR repository where build artifacts are stored, parsed from the configuration"
  pipelines:
    description: "A list of pipeline names, parsed from the configuration"
  devPipelines:
    description: "A list of development pipeline names, parsed from the configuration"
  prodPipelines:
    description: "A list of production pipeline names, parsed from the configuration"
runs:
  using: "node20"
  main: action.mjs
