name: "upload-cdk-source"
description: |
  description: "Create and upload an archive of the CDK source to use during deployment of a Liflig CDK Pipeline"
  local: true
inputs:
  aws-s3-bucket-name:
    description: "The name of the S3 bucket to upload the CDK source to"
    required: true
  include-files:
    description: "A string of space-separated regular expressions that describe which files to include creating the CDK source"
    default: 'assets cdk.json cdk.context.json package.*\.json src tsconfig\.json'
  cdk-app-dir:
    description: |
      Path to the directory that contains the CDK application.

      Defaults to the GitHub workspace directory.

outputs:
  cdk-source-metadata-file:
    description: "The path to a file describing the S3 bucket and S3 key of the uploaded CDK source"
    value: ${{ steps.upload.outputs.cdk-source-metadata-file }}
runs:
  using: "node24"
  main: "dist/index.mjs"
